theme: jekyll-theme-cayman
title: Tristan Guérand - PhD Candidate in Cryptography and Machine Learning
description: PhD Candidate at Nanyang Technological University researching cryptography, machine learning, privacy-preserving ML, and explainable AI
show_downloads : False

owner:
  name: Tristan Guérand
  bio: "This is my personal webpage"
  email : tris.tan.guerand@gmail.com
  linkedin: tristanguerand
  github: tguerand
  avatar: linkedin.jpg

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
