theme: jekyll-theme-cayman
title: Tristan Guérand - Quantitative Researcher
description: Quantitative Researcher at Qube Research and Technologies, previously PhD Candidate in Cryptography and Machine Learning
show_downloads : False

owner:
  name: Tristan Guérand
  bio: "Quantitative Researcher at Qube Research and Technologies, working on High Frequency Signals. Previously PhD Candidate in Cryptography and Machine Learning."
  email : tris.tan.guerand@gmail.com
  linkedin: tristanguerand
  github: tguerand
  avatar: linkedin.jpg

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
